/usr/share/applications/org.gnupg.pinentry-qt.desktop
/usr/share/applications/org.gnupg.pinentry-qt5.desktop
/usr/share/applications/nvim.desktop
/usr/share/applications/avahi-discover.desktop
/usr/share/applications/bssh.desktop
/usr/share/applications/bvnc.desktop
/usr/share/applications/gkbd-keyboard-display.desktop
/usr/share/applications/org.freedesktop.Xwayland.desktop
/usr/share/applications/rofi-theme-selector.desktop
/usr/share/applications/rofi.desktop
/usr/share/applications/io.elementary.granite.demo.desktop
/usr/share/applications/kitty-open.desktop
/usr/share/applications/kitty.desktop
/usr/share/applications/zen.desktop
/usr/share/applications/code-url-handler.desktop
/usr/share/applications/code.desktop
/usr/share/applications/feh.desktop
/usr/share/applications/imv-dir.desktop
/usr/share/applications/imv.desktop
/usr/share/applications/java-java-openjdk.desktop
/usr/share/applications/jconsole-java-openjdk.desktop
/usr/share/applications/jshell-java-openjdk.desktop
/usr/share/applications/org.wezfurlong.wezterm.desktop
/usr/share/applications/yazi.desktop
/usr/share/applications/com.cloudflare.WarpTaskbar.desktop
/usr/share/applications/org.cryptomator.Cryptomator.desktop
/usr/share/applications/nvidia-settings.desktop
/usr/share/applications/electron34.desktop
/usr/share/applications/obsidian.desktop
/usr/share/applications/xfce4-about.desktop
/usr/share/applications/thunar-bulk-rename.desktop
/usr/share/applications/thunar-settings.desktop
/usr/share/applications/thunar.desktop
/usr/share/applications/qv4l2.desktop
/usr/share/applications/qvidcap.desktop
/usr/share/applications/org.pwmt.zathura.desktop
/usr/share/applications/org.pwmt.zathura-pdf-mupdf.desktop
/usr/share/applications/spotify.desktop
/usr/share/applications/gcr-prompter.desktop
/usr/share/applications/gcr-viewer.desktop
/usr/share/applications/org.gnome.seahorse.Application.desktop
/usr/share/applications/vim.desktop
/usr/share/applications/compton.desktop
/usr/share/applications/picom.desktop
/usr/share/applications/timeshift-gtk.desktop
/usr/share/applications/qemu.desktop
/usr/share/applications/electron36.desktop
/usr/share/applications/balena-etcher.desktop
/usr/share/applications/ventoy.desktop
/usr/share/applications/user-dirs-update-gtk.desktop
/usr/share/applications/nautilus-autorun-software.desktop
/usr/share/applications/org.gnome.Nautilus.desktop
/usr/share/applications/gparted.desktop
/usr/share/applications/org.gnome.Zenity.desktop
/usr/share/applications/steam.desktop
/usr/share/applications/com.obsproject.Studio.desktop
/usr/share/applications/lstopo.desktop
/usr/share/applications/org.godotengine.Godot.desktop
/usr/share/applications/vlc.desktop
/usr/share/applications/electron31.desktop
/usr/share/applications/heroic.desktop
/usr/share/applications/wine.desktop
