$terminal = wezterm
$fileManager = wezterm start yazi
$menu = rofi -show drun -theme glass
$switchWall = "$HOME/.config/hypr/scripts/wall.sh"
$kbdBright = "$HOME/.local/bin/asusctl-bright.sh"
$touchpadToggle = "$HOME/.local/bin/touchpad.sh"

source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/appearance.conf
source = ~/.config/hypr/conf/animations.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/window.conf
